builds:
  -
    binary: log-checker
    ldflags:
      - -s -w 
      - -X github.com/thetherington/log-checker/cmd.Version={{.Version}}
      - -X github.com/thetherington/log-checker/cmd.Commit={{.Commit}}
      - -X github.com/thetherington/log-checker/cmd.Date={{.Date}}
      - -X github.com/thetherington/log-checker/cmd.BuiltBy=goreleaser